### PR TITLE
[AAE-3810] fix ADF app when mounted on root context

### PR DESCRIPTION
**Pull request by eromano**
Update ADF app chart, see AAE-3810

### CODE REVIEW

**Review by mteodori — APPROVED** [review]

**Comment by gavincornwell** [comment]
We need to run this through the full build as last time I tried upgrading this chart it failed. The Travis build however only runs on branches following the pattern "feature/XYZ". 

I will create another branch from this one to execute the build and let you know, please don't merge until then!

**Comment by gavincornwell** [comment]
Build running here: https://travis-ci.com/github/Alfresco/acs-deployment/builds/188887250

**Review by gavincornwell — CHANGES_REQUESTED** [review]
As I suspected the build failed (https://travis-ci.com/github/Alfresco/acs-deployment/jobs/397086851), when calling /workspace a 500 error occurs.

Lets discuss how to move forward in the morning.

**Review by gavincornwell — APPROVED** [review]
The build from my branch now appears to be green so LGTM.

**Pull request merged**
