### PR TITLE
SEARCH-1260: Update Solr memory setting on AWS 

### PR DESCRIPTION
**Pull request by tunaaksoy**

### CODE REVIEW

**Comment by derekhulley** [comment]
Next release is https://issues.alfresco.com/jira/browse/REPO-3986

**Comment by tunaaksoy** [comment]
I just used the ticket number I got. I was under the impression the release was not rolled out yet. It should not matter though. The change can be merged and it'll be ready for the next RC.

**Comment by derekhulley** [comment]
This is "deployment", so a release can be done for an updated Search Services at any time.  The RC1 artifacts for ACS were produced earlier today and have gone into deployment, already.
Also, you will want to update the VERSIONS.md file in acs-packaging.

**Comment by tunaaksoy** [comment]
Build is green: https://bamboo.alfresco.com/bamboo/browse/PLAT-ACSHELM105-6

**Pull request merged**
