### PR TITLE
Added Default encoding to resolve unizp issue

### PR DESCRIPTION
**Pull request by pardhukota-pk**
Added jvm args for encoding in docker file that sets the default encoding as UTF8 and hence resolve the file name issue that is blocking the user to unzip files with accent characters in filename.

### CODE REVIEW

**Review by gionn — COMMENTED** [review]
I suspect we are not correctly setting the default locale in the base image, this changes should not be necessary

**Comment by alxgomz** [comment]
@pardhukota-pk ,
If I provide you with a new tomcat image with correct env vars, ca nyou test the scenario again (so we can simply drop that PR)?

**Comment by pardhukota-pk** [comment]
> @pardhukota-pk , If I provide you with a new tomcat image with correct env vars, ca nyou test the scenario again (so we can simply drop that PR)?

I will take help from @MohinishSah and can test it.

**Comment by pardhukota-pk** [comment]
> @pardhukota-pk , If I provide you with a new tomcat image with correct env vars, ca nyou test the scenario again (so we can simply drop that PR)?

@alxgomz Can you please share the latest tomcat image ?

**Comment by alxgomz** [comment]
Please test with quay.io/alfresco/alfresco-base-tomcat:tomcat9-jdk17-rockylinux8-OPSEXP-2136-202306071035

**Comment by pardhukota-pk** [comment]
> Please test with quay.io/alfresco/alfresco-base-tomcat:tomcat9-jdk17-rockylinux8-[OPSEXP-2136](https://alfresco.atlassian.net/browse/OPSEXP-2136)-202306071035 and let me if it helps.

@alxgomz I tested with the above tomcat image and it didn't resolve the issue. I still see the error when I try to unzip the file with accent in its name. I updated the above image in the below Dockerfiles and built and tested it
C:\SourceCode\BuildScripts\alfresco-enterprise-share\packaging\docker\Dockerfile
C:\SourceCode\BuildScripts\alfresco-enterprise-repo\packaging\docker-alfresco\Dockerfile
C:\SourceCode\BuildScripts\alfresco-community-repo\packaging\docker-alfresco\Dockerfile

**Comment by alxgomz** [comment]
As checked with @pardhukota-pk, these changes do not resolve the issue. Also, we are about to release new tomcat & java images which will essentially provide UTF-8 as the the default for collation & language settings, hence dropping the need for these options.

**Pull request closed without merging**
