### PR TITLE
bump sync service from 3.3.3.1 to 3.4.0-M2

### PR DESCRIPTION
**Pull request by ciprianchelaru**

### CODE REVIEW

**Comment by gavincornwell** [comment]
@ciprianchelaru What version of ACS is sync-service 3.4.0-M2 supporting 6.2.2 and 7.0 or just 7.0?

**Comment by ciprianchelaru** [comment]
> @ciprianchelaru What version of ACS is sync-service 3.4.0-M2 supporting 6.2.2 and 7.0 or just 7.0?

**Comment by ciprianchelaru** [comment]
> > @ciprianchelaru What version of ACS is sync-service 3.4.0-M2 supporting 6.2.2 and 7.0 or just 7.0?

is just 7.0

**Comment by gavincornwell** [comment]
OK, in that case we need to make some other changes, do you mind if I update your branch?

**Comment by ciprianchelaru** [comment]
> OK, in that case we need to make some other changes, do you mind if I update your branch?

no no, it's fine. I didn't know that also I should do  other changes

**Comment by gavincornwell** [comment]
Done. These are one time changes as we need to have a different version of sync for 6.2.x and 7.0.

**Review by ciprianchelaru — COMMENTED** [review]
LGTM

**Review by gavincornwell — APPROVED** [review]
Build is green so LGTM

**Pull request merged**
