### PR TITLE
ACA-1847: integrate Digital Workspace image

### PR DESCRIPTION
**Pull request by DenysVuika**
## Details

The PR adds extra Alfresco Digital Workspace 1.0.0 from quay.io.
Also, it adds an ingress container to solve the CORS problems and proxy the repository for ADW.
The resulting application is served at port 8080, as well as Share and Alfresco.

## Testing

```sh
docker-compose up
open http://localhost:8080
```

Use default `admin:admin` to log into the app.

### CODE REVIEW

**Comment by derekhulley** [comment]
This change looks good.
We requested some postman tests, which we'll incorporate into the build to ensure that the application is actually exposed and running.

**Comment by DenysVuika** [comment]
@derekhulley The test for Share uses the following url `https://{{url}}/share/page/modules/deploy`. And share is on port 8080. What will be the test for ADW running on port 8084 ?

**Comment by derekhulley** [comment]
You need to find a URL that, if successfully called, means that your application is up and running.  We don't know which URL that would be for the ADW image.

**Comment by DenysVuika** [comment]
I am closing this PR as the amount of requirements is far beyond a single person and requires cross-team collaboration.

**Comment by DenysVuika** [comment]
It will also take couple of days to setup the Helm integration. The added requirement is not yet published and the work is in progress.

**Comment by skopf** [comment]
Please see this Bamboo build:
https://bamboo.alfresco.com/bamboo/browse/PLAT-ACSHELM85-DI-4
We cannot merge broken branches to master.

About the ADW Helm Charts:
I thought that we already have these Helm Charts?

**Comment by DenysVuika** [comment]
@skopf ADW images are new and not yet released/announced. we are working on that for the moment. I will remove `WIP` prefix from the PR once helm thing is solved, thanks.

**Comment by DenysVuika** [comment]
@derekhulley @skopf @john-knowles I don't understand anything from the ACS configuration settings, and have absolutely no idea what else needs to be changed. For now the CI/CD fails, apparently it can serve/find the app and I am out of ideas what to do.

**Comment by DenysVuika** [comment]
@skopf there's a helm chart already and I see it being fetched successfully in CI/CD. However, the endpoint `/digital-workspace` is not available. Do I need to add more configuration options somewhere?

**Comment by killerboot** [comment]
The docker-compose is good to go. I run the TAS tests against a similar configuration on acs-packaging project and the proxy passed all of them.

Once you will be ready to release the proxy, please rename the image (and opensource it probably) as it is going to be part of ACS from now on.

The final change. Can you please update the diagrams here:
https://github.com/Alfresco/acs-deployment/tree/master/docs/diagrams/docker-compose

**Pull request merged**
