### PR TITLE
SEARCH-817 (Extract search services to separate helm chart)

### PR DESCRIPTION
**Pull request by tunaaksoy**

### CODE REVIEW

**Comment by andrei-rebegea** [comment]
Changes look good to me. But I prefer someone from PS team to also do a review.

**Comment by tunaaksoy** [comment]
@derekhulley  Sorry, I do not understand your comment. What kind of guarantees you are you looking for? What kind of guarantees do we have for any of our charts?

**Comment by killerboot** [comment]
LGTM, assuming that the search services chart is present in http://kubernetes-charts.alfresco.com/incubator

**Comment by tunaaksoy** [comment]
@killerboot yes, it is available. I pushed the chart for alfresco-search-services first otherwise I'd "break" acs-deployment/acs-community-deployment. I have tested alfresco-search-services with both projects. You can find the chart here https://github.com/Alfresco/charts/tree/master/incubator

**Pull request merged**
