### PR TITLE
OPSEXP-1374: Fix ooi and ms teams service - http 404 error

### PR DESCRIPTION
**Pull request by Mieszko96**
Ref. OPSEXP-1374

### CODE REVIEW

**Review by MichalFidor — APPROVED** [review]

**Review by montgolfiere — APPROVED** [review]

**Review by montgolfiere — CHANGES_REQUESTED** [review]
If it works then LGTM.

Same may apply to other (optional) external API endpoints, eg. /ms-teams-service ?

https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/templates/ingress-ms-teams-service.yaml#L12

**Review by alxgomz — APPROVED** [review]
LGTM

**Review by montgolfiere — APPROVED** [review]
Thanks

**Review by mteodori — APPROVED** [review]
LGTM, those annotations seem incorrect anyway as they are not configurable while ingress.path is

**Pull request merged**
