### PR TITLE
SEARCH-825 (Create a helm chart for Alfresco Zeppelin) (#28)

### PR DESCRIPTION
**Pull request by tunaaksoy**
SEARCH-825 (Create a helm chart for Alfresco Zeppelin)

### CODE REVIEW

**Comment by tunaaksoy** [comment]
Is the release process described somewhere? Next time I can do the release if you want.

I think all you need to do is to merge this PR to support/HF/1.0, update Chart.yaml and helm-chart-releases.md files. Once the build on support/HF/1.0 is green then release it from there. Not so sure if I missed any steps.

**Comment by killerboot** [comment]
I noticed that insight engine is not started up by default. Is it intentional?
The tests on a branch will not pass as the number of pods was wrong. I corrected the number back to 10, should pass now.

**Comment by tunaaksoy** [comment]
Yes, that's intentional. I did not want to change the existing behaviour. For you nothing will change. You have the option to swap Search Services with Insight Engine if you want but you need to specify that (--set alfresco-search.type="insight-engine" --set alfresco-search.registryPullSecrets="quay-registry-secret"). Also Zeppelin has be explicitly enabled (--set alfresco-insight-zeppelin.enabled="true" --set alfresco-search.alfresco-insight-zeppelin.registryPullSecrets="quay-registry-secret") otherwise it won't be available.

**Comment by tunaaksoy** [comment]
Thanks for fixing the number of pods. I was not so sure if the number of pods was correct or not.

**Comment by tunaaksoy** [comment]
The bamboo build is green.

**Pull request merged**
