### PR TITLE
OPSEXP-105: Minor tweak to Community Docker Compose diagram

### PR DESCRIPTION
**Pull request by montgolfiere**
- Core AIO does not connect to ActiveMQ (for Community ref deployment)
- eg. see

https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml#L48-L54
https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml#L69-L79

### CODE REVIEW

**Review by gparapadakis — APPROVED** [review]

**Comment by montgolfiere** [comment]
@gavincornwell Noticed this after chatting with @gparapadakis.

As an aside (maybe a separate PR) we could also look to tweak the Enterprise diagrams for both docker-compose and helm. The T-Engines also call ActiveMQ. However, I'm not sure how well it would display for the helm/k8s option with so many crossing lines.

**Review by gavincornwell — COMMENTED** [review]
Has the image generated correctly, shows as empty!?

**Comment by montgolfiere** [comment]
I think so. I can download it :-) 

Maybe a GitHub web ui issue ?

If you click on rich diff you can see Before and After.

**Comment by gavincornwell** [comment]
Hmm, you're right, is showing correctly now!?

**Review by gavincornwell — APPROVED** [review]

**Pull request merged**
