### PR TITLE
ATS-230 : Release ATS 1.0.0

### PR DESCRIPTION
**Pull request by DenisGabriela**

### CODE REVIEW

**Comment by killerboot** [comment]
Please check if this is working with ACS on EKS running with AmazonMQ.

**Comment by montgolfiere** [comment]
@killerboot  Do you mean via https://github.com/Alfresco/acs-deployment-aws stack deployment ? If so, then that is a good idea. However, I don't believe anyone in InT have tried or used that overlaid deployment mechanism. 

We may need a separarte post-merge verification task or else someone can describe quick steps to hook in a acs-deployment feature branch into acs-deployment-aws.

**Comment by killerboot** [comment]
@montgolfiere Yes, this repo (https://github.com/Alfresco/acs-deployment-aws) uses this chart (not exactly this version of chart) to deploy and test ACS on EKS.
You can create a branch there and make sure it is using the chart you need to test against it and watch the build plan results.

**Comment by montgolfiere** [comment]
@killerboot Thanks - although not sure which build/results. Does this also relate to https://issues.alfresco.com/jira/browse/REPO-4067 ?

@DenisGabriela @aftene @CezarLeahu @tzclucian please see above :-)

**Comment by killerboot** [comment]
@montgolfiere See the following build plan https://bamboo.alfresco.com/bamboo/browse/PLAT-ADA
It may require adding extra tests if you need them on this level.

**Comment by tzclucian** [comment]
They've picked me to press the button. Fingers crossed.

**Pull request merged**
