### PR TITLE
Bump to ADW 2.0.0

### PR DESCRIPTION
**Pull request by montgolfiere**
- note: 2.0.0-adw (rather than 2.0.0)
- note: both master (7.0.0-Mx) *and* 6.2.N since new ADW / OOI extension targets ACS 6.2.2 or higher

### CODE REVIEW

**Review by KikoUK — APPROVED** [review]
LGTM

**Comment by gavincornwell** [comment]
@montgolfiere Why "2.0.0-adw" and not "2.0.0"? Is the OOI support only in "-adw"?

**Comment by montgolfiere** [comment]
@gavincornwell It won't start properly. It seems 2.0.0 contains the APA code and the plugin is enabled by default (requested by PaaS). Hence as per @mauriziovitale it is better to use 2.0.0-adw

**Review by gavincornwell — APPROVED** [review]
LGTM

**Pull request merged**
