### PR TITLE
WIP: Experiment: SEARCH-1305: speedup packaging of Helm chart on dev environment

### PR DESCRIPTION
**Pull request by paulbrodner**
**Features:**
within "_helm/alfresco-content-services_" folder:
* ability to bump up the new release version automatically: `make tag` (and also push it to repository if we want `make release-tag`)
* ability to build or package the chart: `make package`
* ability to build or package the chart, not skipping the local helm repository: `make local-repo package`

**Note:**
You can mix the commands if you like: `make tag release-tag package` (this should auto-increment the version, commit the tag and push the updated Chart.yaml to repo

### CODE REVIEW

**Comment by derekhulley** [comment]
This looks interesting.
Can you point to the equivalent changes in https://github.com/Alfresco/alfresco-search-deployment?

**Comment by tunaaksoy** [comment]
The equivalent changes on our side can be found here: https://github.com/Alfresco/alfresco-search-deployment/pull/10

This is currently in review/verify state on our end.

**Comment by paulbrodner** [comment]
@derekhulley as an overview, checkout this https://issues.alfresco.com/jira/browse/SEARCH-1305

**Comment by derekhulley** [comment]
OK.  Now the change makes sense.
Note that the requirement to have a branch, a green build and a merge means that you can't update the _requirements_ during the release process.  We could relax some requirements but a green build on master should be considered a minimum (obviously) before charts are released.

**Comment by tunaaksoy** [comment]
My concern is that we have the same files (new-version.sh and Makefile) in both projects and to maintain them will be difficult. Make file in this repo has one more target for starting up a local helm repo but there is no other change in the files. And if we think of other helm charts which might become a requirement for ACS helm chart will we apply the same pattern for them as well? It will be optional I think but there is a chance to use the files there as well which will make maintenance a problem. Not so sure if someone fixes an issue in the files in this repo will also make sure to fix the same issue in our chart (and probably others).

We also need to be careful when bumping up version numbers. It's OK locally but it's very easy to push that change as part of a PR/MR. You are not supposed to bump up the version every time when you commit. There is no hard rules though as far as I am aware of.

**Comment by killerboot** [comment]
I'll close this PR, but leave the branch if you still need it.

**Pull request closed without merging**
