### PR TITLE
ATS-251 : Release ATS 1.0.1 (~ target ACS 6.1.0 final)

### PR DESCRIPTION
**Pull request by DenisGabriela**

### CODE REVIEW

**Comment by DenisGabriela** [comment]
Thanks. Will merge it once the build is green.

**Comment by montgolfiere** [comment]
@DenisGabriela Thanks for including SFS 0.5.2 (~ REPO-4172) for compleness 👍

**Comment by montgolfiere** [comment]
Any news on getting green build on PLAT-ACSHELM *master* and then branch builds ... to unblock this merge request ?

**Comment by killerboot** [comment]
@montgolfiere it looks like helm version was updated on the build agents:
incompatible versions client[v2.12.2] server[v2.9.1]
I will take a look.

**Comment by killerboot** [comment]
Master is green again

**Pull request merged**
