### PR TITLE
REPO-4670: Update helm chart docker image information

### PR DESCRIPTION
**Pull request by amohammedalfresco**
- Extend [docs/helm-chart-releases.md](https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-chart-releases.md) file with docker image information which is part of ACS Helm chart.

### CODE REVIEW

**Comment by amohammedalfresco** [comment]
Thanks @killerboot! The (MNT-20924)[https://issues.alfresco.com/jira/browse/MNT-20924] is requesting for this information against each ACS helm chart release.

**Comment by montgolfiere** [comment]
Also, means another place to remember (or forget) to maintain docker image versions (in addition to helm chart values & docker-compose files) ?

**Comment by ancutam** [comment]
That's a lot of work, Abdul! But unless it is generated somehow, I don't see how we will maintain it.

**Comment by amohammedalfresco** [comment]
It seems maintaining this piece of information is going to be a task of its own due to a need of any automation and also duplication of information.

Hence, for the time being I will close this PR and update the requester about it.

**Pull request closed without merging**
